title: "Kings Mobile Welding Blog"
description: "Updates, project highlights, and welding know-how from the field."
url: "https://amexclawback.github.io"   # user/organization pages: keep baseurl empty
baseurl: ""                              # overridden to /blog during Kings build
timezone: "America/New_York"

markdown: kramdown
theme: jekyll-theme-chirpy

plugins:
  - jekyll-feed
  - jekyll-seo-tag

collections:
  posts:
    output: true
    permalink: /posts/:title/

# Force posts to use our layout (your workflow also sets this during /blog build)
defaults:
  - scope:
      path: ""
      type: "posts"
    values:
      layout: "post"

# Keep Jekyll from picking up junk
exclude:
  - node_modules
  - vendor/bundle
  - Gemfile.lock
  - package-lock.json
'@ | Set-Content -Encoding UTF8 -NoNewline .\_config.yml

