name: Build blog and sync to Kings site

on:
  push:
    branches: [ main ]     # runs immediately when you publish (push to main)
  workflow_dispatch: {}     # allow manual runs if needed

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout blog
        uses: actions/checkout@v4

      - name: Setup Ruby
        uses: ruby/setup-ruby@v1
        with:
          ruby-version: '3.2'
          bundler-cache: true

      - name: Install deps
        run: bundle install

      # Build with /blog baseurl so links work under your website's /blog
      - name: Build Jekyll for /blog
        run: |
          echo 'url: "https://www.kingsmobilewelding.com"' > _config.kmw.yml
          echo 'baseurl: "/blog"' >> _config.kmw.yml
          bundle exec jekyll build --trace --config _config.yml,_config.kmw.yml

      # (Optional) stage feed.xml separately so your site has the latest /assets/feed.xml too
      - name: Prepare feed.xml
        run: |
          mkdir -p push-assets
          cp ./_site/feed.xml push-assets/feed.xml

      # Push built blog into your site repo under /blog (instant publish)
      - name: Push built blog to KingsMobileWelding/blog
        uses: peaceiris/actions-gh-pages@v3
        with:
          personal_token: ${{ secrets.KMW_SYNC_TOKEN }}   # PAT with Contents:write to KingsMobileWelding
          external_repository: AmexClawBack/KingsMobileWelding
          publish_branch: main
          publish_dir: ./_site
          destination_dir: blog
          keep_files: true
          user_name: "github-actions[bot]"
          user_email: "github-actions[bot]@users.noreply.github.com"

      # Push the fresh feed into /assets (keeps your viewer/blog.html happy)
      - name: Push feed.xml to KingsMobileWelding/assets
        uses: peaceiris/actions-gh-pages@v3
        with:
          personal_token: ${{ secrets.KMW_SYNC_TOKEN }}
          external_repository: AmexClawBack/KingsMobileWelding
          publish_branch: main
          publish_dir: ./push-assets
          destination_dir: assets
          keep_files: true
          user_name: "github-actions[bot]"
          user_email: "github-actions[bot]@users.noreply.github.com"
